#%RAML 1.0
#baseUri: http://www.tshirt.com/api
baseUri: http://mocksvc.mulesoft.com/mocks/a2126894-176f-4892-b21a-0cd998bcdcdb/api
title: T-Shirt Ordering Service
version: 1.0.development
mediaType: [application/json]
protocols: [ HTTPS ]
securitySchemes:
  - oauth_2_0:
securedBy: [ oauth_2_0 ]

/orders:
  displayName: Orders
  description: Orders collection resource used to create new orders.
  get:
    description: lists all orders of a specific user
    queryParameters:
      userId:
        type: string
        description: use to query all orders of a user
        required: true
        example: 1964401a-a8b3-40c1-b86e-d8b9f75b5842
      size:
        description: the amount of elements of each result page
        type: integer
        required: false
        example: 10
      page:
        description: the page number
        type: integer
        required: false
        example: 0
    responses:
      200:
        body:
          application/json:
            type: object
            properties:
              orders:
                type: array
                items:
                  type: object
                  properties:
                    order_id: string
                    creation_date: string
                    items:
                      type: array
                      items:
                        type: object
                        properties:
                          product_id: string
                          quantity: integer
/status:
  displayName: Status
  description: Status of the order.
  post:
    description: Gives the status of the order
    queryParameters:
      id:
        required: true
        type: integer
        description: order id
        example: 29845754
    body:
      application/xml:
        formParameters:
          account:
            required: true
            type: string
            description: User account
            example: myAccount123
    responses:
      200:
        body:
          application/json
/returns{id}:
  displayName: Returns
  description: Order to return
  uriParameters:
    id:
      description: Order id
      required: true
      type: integer
      example: 0932457
  post:
    body:
      application/x-www-form-urlencoded:
        formParameters:
          size:
            type: string
            required: true
            description: size of the item
            enum: [ S, M, L ]
          account:
            type: string
            description: User account
            required: true
            example: myAccount123
    responses:
      200:
        body:
          application/json
/available:
  description: Checks availability of item
  post:
    body:
      multipart/form-data:
        formParameters:
          itemId:
            required: true
            type: string
            example: sdf9870
          size:
            description: Size of item
            required: true
            type: string
            example: M
          color:
            description: Color of item
            required: true
            type: string
            example: blue
    responses:
      200:
        body:
          application/xml