#%RAML 1.0
#baseUri: http://www.tshirt.com/api
baseUri: http://mocksvc.mulesoft.com/mocks/a2126894-176f-4892-b21a-0cd998bcdcdb/api
title: T-Shirt Ordering Service
version: 1.0.development
mediaType: [application/json]
protocols: [ HTTPS ]
securitySchemes:
  - oauth_2_0:
securedBy: [ oauth_2_0 ]

/orders{account}:
  uriParameters:
    account:
      description: account id
      type: string
      enum: [myaccount123, newaccount987]
  displayName: Orders
  description: Orders collection resource used to create new orders.
  get:
    description: lists all orders of a specific user
    queryParameters:
      size:
        description: the amount of elements of each result page
        type: integer
      page:
        description: the page number
        required: false
        example: 10
    body:
      multipart/form-data:
    responses:
      200:
        body:
/status:
  displayName: Status
  description: Status of the order.
  get:
    description: Gives the status of the order
    queryParameters:
      id:
        type: string
    body:
      application/xml:
        formParameters:
          account:
            required: true
    responses:
      200:
        body:
          application/json
/returns{id}:
  uriParameters:
    id:
      example: 0932457
  displayName: Returns
  post:
    body:
      application/x-www-form-urlencoded:
        formParameters:
          size:
            description: size of the item
            enum: [ S, M, L ]
          account:
            description: account number
    responses:
      200:
        body:
/available:
  description: checks availability of item
  post:
    body:
      multipart/form-data:
        formParameters:
          itemId:
            example: sdf9870
          size:
            description: size of item
          color:
            required: true
    responses:
      200:
        body: