#%RAML 1.0
#baseUri: http://www.tshirt.com/api
baseUri: http://mocksvc.mulesoft.com/mocks/a2126894-176f-4892-b21a-0cd998bcdcdb/api
title: T-Shirt Ordering Service
version: 1.0.development
mediaType: [application/json]
protocols: [ HTTPS ]
securitySchemes:
  - oauth_2_0:
securedBy: [ oauth_2_0 ]
types:
  Shirts:
    type: array
    items: shirt
  shirt:
    type: object
    properties:
      size: number
      productCode: string
      description: string

/orders:
  displayName: Orders
  description: Orders collection resource used to create new orders.
  get:
    description: lists all orders of a specific user
    queryParameters:
      userId:
        type: string
        description: use to query all orders of a user
      size:
        description: the amount of elements of each result page
        type: integer
      page:
        description: the page number
        required: false
    responses:
      200:
        body: